### ISSUE TITLE
Releases and versions.

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [aniqfakhrul/Sharperner#3]
It'd be cool if we didn't have to build the releases ourselves. There is also currently no distinction from versions, which might cause problems with debugging in the future.
Anyway, here's a build for commit b272685 (Built on 2021-08-31): https://mega.nz/file/BtwGWYrR#UQUipia3UWR2WR-Wg6bg11f4BGUj9TEiTqFgBI1UQ4M

**Comment by aniqfakhrul** [comment]
Ill take this into consideration. Yeah few people were having difficulties installing dependencies. Will update in the future.
